language: node_js

node_js:
  - "8"

cache:
  directories:
  - "$HOME/google-cloud-sdk"
  - "node_modules"


env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
  - PROJECT_NAME=supple-bank-232805
  - CLUSTER_NAME=big-data-node-api-cluster
  - CLOUDSDK_COMPUTE_ZONE=us-central1-c

before_install:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update beta
  - gcloud --quiet components update kubectl
  - echo $super_secret_password | gpg --passphrase-fd 0 My-project-key.json.gpg
  - echo $super_secret_password | gpg --passphrase-fd 0 ./config/LogstashConfig.js.gpg
  - echo $super_secret_password | gpg --passphrase-fd 0 ./config/RedisConfig.js.gpg
  - echo $super_secret_password | gpg --passphrase-fd 0 ./config/ServerConfig.js.gpg
  - echo $super_secret_password | gpg --passphrase-fd 0 ./config/TwitterConfig.js.gpg
  - ls -l ./config/

install:
  - npm install
  - docker

script:
  - echo "success installing."
  - pwd
  - ls -l

before_deploy:
  - gcloud --quiet components update kubectl

  deploy:
  - provider: script
    script: bash ./deploy-node.sh
    skip_cleanup: true
    on:
      branch: master