apiVersion: v1
kind: Service
metadata:
  labels:
    run: big-data-node-api-cluster
  name: big-data-node-api-cluster
  namespace: default
spec:
  ports:
  - name: api
    port: 3000
    protocol: TCP
    targetPort: 3000
  - name: websock
    port: 34234
    protocol: TCP
    targetPort: 34234
  selector:
    run: big-data-node-api-cluster
  sessionAffinity: None
  type: LoadBalancer
