apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: big-data-node-api-cluster
  name: big-data-node-api-cluster
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: big-data-node-api-cluster
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: big-data-node-api-cluster
    spec:
      containers:
      - image: gcr.io/supple-bank-232805/big-data-node-api-cluster:latest
        imagePullPolicy: Always
        name: big-data-node-api-cluster
        ports:
        - containerPort: 3000
          protocol: TCP
        - containerPort: 34234
          protocol: TCP
        resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

